### PR TITLE
Create podman-desktop-e2e-windows.yaml

### PR DESCRIPTION
**Pull request by odockal**

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
hi, what's the difference with https://github.com/containers/podman-desktop-e2e/blob/main/.github/workflows/windows.yaml ?

shouldn't it be merged in the same launch ?

**Comment by benoitf** [comment]
@odockal ?

**Comment by adrianriobo** [comment]
yeah :) +1

**Comment by adrianriobo** [comment]
yeah also `rebase and merge` instead of `merge` I totally forgot on that and was not understanding why there were 2 commits

**Pull request merged**
